import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {compileCachePlan,invalidateCompileCache} from '../lib/compile-cache.mjs';
function temp(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mp2-compile-cache-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return dir;}
test('cache plan is read-only and invalidation preserves exact generated bytes',t=>{
  const dir=temp(t),acf=path.join(dir,'demo.acf'),source=path.join(dir,'demo.gdf'),cache=path.join(dir,'demo.cnf'),content=Buffer.from([0,1,2,255]);fs.writeFileSync(acf,'CHIP demo\nBEGIN\nEND;');fs.writeFileSync(source,'source');fs.writeFileSync(cache,content);
  assert.equal(compileCachePlan(acf).available,true);assert.deepEqual(fs.readFileSync(cache),content);assert.equal(fs.existsSync(path.join(dir,'.mcp-backups')),false);
  const result=invalidateCompileCache(acf);assert.equal(result.invalidated,true);assert.deepEqual(fs.readFileSync(result.backup),content);assert.equal(fs.existsSync(cache),false);assert.ok(result.backup.startsWith(dir+path.sep));assert.equal(fs.readFileSync(source,'utf8'),'source');
});
test('a CNF-only project and explicitly requested incremental compilation preserve their input',t=>{
  const dir=temp(t),acf=path.join(dir,'demo.acf'),cache=path.join(dir,'demo.cnf');fs.writeFileSync(acf,'CHIP demo\nBEGIN\nEND;');fs.writeFileSync(cache,'only design input');
  assert.equal(invalidateCompileCache(acf).invalidated,false);fs.writeFileSync(path.join(dir,'demo.v'),'module demo;endmodule');assert.equal(invalidateCompileCache(acf,{enabled:false}).invalidated,false);assert.equal(fs.readFileSync(cache,'utf8'),'only design input');
});
test('generated cache invalidation never touches another basename',t=>{
  const dir=temp(t),acf=path.join(dir,'demo.acf');fs.writeFileSync(acf,'');fs.writeFileSync(path.join(dir,'demo.vhd'),'source');fs.writeFileSync(path.join(dir,'other.cnf'),'preserve');const r=invalidateCompileCache(acf);assert.equal(r.invalidated,false);assert.equal(fs.readFileSync(path.join(dir,'other.cnf'),'utf8'),'preserve');
});
