import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createBlankGdf,constructGdf} from '../lib/gdf-authoring.mjs';
import {sha256} from '../lib/workspace.mjs';
import {parseGdfGeometry,tokeniseGdfGeometry} from '../lib/gdf-geometry.mjs';
import {inspectGdfConnections,gdfTerminalPartitions,gdfSignalName} from '../lib/gdf-connections.mjs';
import {moveGdfConnected} from '../lib/gdf-connected-editor.mjs';
const root=process.env.MAXPLUS2_ROOT??'C:/maxplus2';
export function xorFixture(){const ops=[],sources=new Map();for(const [s,name,x,y,nodeName] of [['input','inputA',32,296,'A'],['input','inputB',32,280,'B'],['xor','gate',272,280],['output','outputY',408,288,'Y']]){const bytes=fs.readFileSync(`${root}/max2lib/prim/${s}.sym`);sources.set(s,bytes);ops.push({operation:'add_symbol',symbolPath:s,symbolSha256:sha256(bytes),name,x,y,...(nodeName?{nodeName}:{})});}for(const [x1,y1,x2,y2] of [[200,304,272,304],[200,288,272,288],[336,296,408,296]])ops.push({operation:'add_wire',x1,y1,x2,y2});return constructGdf(createBlankGdf(),ops,s=>({path:s,bytes:sources.get(s)})).buffer;}
const gate=b=>parseGdfGeometry(b).placements.find(p=>p.instanceName==='gate');
test('source graph preserves unsynthesized gate and six native pin identities',()=>{const m=inspectGdfConnections(xorFixture());assert.equal(m.completeScalarTopology,true);assert.deepEqual(m.nets.map(n=>n.names),[['A'],['B'],['Y']]);assert.deepEqual(m.nets.map(n=>n.terminals.map(t=>t.instanceName)),[['inputA','gate'],['inputB','gate'],['gate','outputY']]);assert.deepEqual(m.diagnostics,[]);});
test('perpendicular T needs both endpoints, collinear overlap joins, dots do not bridge',()=>{const make=ops=>constructGdf(createBlankGdf(),ops,()=>{}).buffer,w=(x1,y1,x2,y2,extra={})=>({operation:'add_wire',x1,y1,x2,y2,...extra});assert.equal(inspectGdfConnections(make([w(0,16,64,16),w(32,0,32,64)])).counts.nets,2);assert.equal(inspectGdfConnections(make([w(0,16,64,16),w(32,16,32,64,{startDot:true})])).counts.nets,2);assert.equal(inspectGdfConnections(make([w(0,16,32,16),w(32,16,64,16),w(32,16,32,64)])).counts.nets,1);assert.equal(inspectGdfConnections(make([w(0,16,64,16),w(32,16,96,16)])).counts.nets,1);});
test('simple translations and all native orientations preserve independently specified scalar pairs',()=>{const b=xorFixture(),expected=gdfTerminalPartitions(inspectGdfConnections(b)),digest=sha256(b);for(const e of [{dy:64},{dx:96},{dx:32},{dx:-32},...Array.from({length:8},(_,orientation)=>({dx:16,dy:64,orientation}))]){const r=moveGdfConnected(b,{edits:[{recordOffset:gate(b).offset,...e}]});assert.equal(r.connectionCheck.preserved,true);assert.deepEqual(gdfTerminalPartitions(inspectGdfConnections(r.buffer)),expected);assert.equal(sha256(b),digest);}});
test('moving a pin off a wire interior splits the old mainline and retains its annotation bytes',()=>{let b=xorFixture();const g=parseGdfGeometry(b),wire=g.sheet.wires.find(w=>w.start.y===304);b=constructGdf(b,[{operation:'delete_wire',recordOffset:wire.offset},{operation:'add_wire',x1:200,y1:304,x2:400,y2:304,nodeName:'A'}],()=>{}).buffer;const q=tokeniseGdfGeometry(b).find(t=>t.nativeType===11&&t.attrType===6),before=inspectGdfConnections(b),r=moveGdfConnected(b,{edits:[{recordOffset:gate(b).offset,dy:64}]});assert.ok(r.connectionCheck.splitWires>0);assert.deepEqual(gdfTerminalPartitions(inspectGdfConnections(r.buffer)),gdfTerminalPartitions(before));assert.ok(tokeniseGdfGeometry(r.buffer).some(t=>t.opcode==='q'&&t.body.equals(q.body)));});
test('unconnected placement movement creates no pointless route and preserves pins',()=>{const b=constructGdf(xorFixture(),[{operation:'delete_wire',recordOffset:parseGdfGeometry(xorFixture()).sheet.wires.find(w=>w.start.y===304).offset}],()=>{}).buffer,r=moveGdfConnected(b,{edits:[{recordOffset:gate(b).offset,dy:64}]});assert.equal(r.changes.filter(c=>c.operation==='reconnect_pin').some(c=>c.pin==='2'),false);assert.equal(r.connectionCheck.preserved,true);});
test('invalid grids, duplicate selections, buses, unknown labels and impossible pin collisions fail atomically',()=>{const b=xorFixture(),p=gate(b).offset,digest=sha256(b);for(const edits of [[{recordOffset:p,dx:1}],[{recordOffset:p,dy:8},{recordOffset:p,dy:16}],[{recordOffset:0,dy:8}],[{recordOffset:p}],[{recordOffset:p,typo:8}],[{recordOffset:p,dy:16}]])assert.throws(()=>moveGdfConnected(b,{edits}));const bus=constructGdf(b,[{operation:'add_wire',x1:0,y1:0,x2:64,y2:0,bus:true,nodeName:'D[3..0]'}],()=>{}).buffer;assert.throws(()=>moveGdfConnected(bus,{edits:[{recordOffset:gate(bus).offset,dy:64}]}),/scalar topology/);assert.equal(sha256(b),digest);assert.throws(()=>moveGdfConnected(b,{edits:[{recordOffset:p,dx:10000}],maxRouteSteps:100}),/budget/);});
test('bus declarations reuse bounded expansion and unsafe large single-bit indices cannot alias',()=>{assert.equal(gdfSignalName('A[9007199254740992]'),null);assert.equal(gdfSignalName('A[9007199254740993]'),null);const make=(count,names)=>constructGdf(createBlankGdf(),Array.from({length:count},(_,i)=>({operation:'add_wire',x1:0,y1:i*8,x2:64,y2:i*8,bus:true,nodeName:names(i)})),()=>{}).buffer;const m=inspectGdfConnections(make(1000,()=>'A[4000..0]'));assert.equal(m.expandedMembers,4001);assert.equal(m.completeScalarTopology,false);assert.equal(new Set(m.nets.flatMap(n=>n.members??[]).map(m=>m.members)).size,1);assert.throws(()=>inspectGdfConnections(make(30,i=>`A${i}[4000..0]`)),/member expansion budget/);});
