import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createSymbol,editSymbol,inspectSymbol} from '../lib/gdf-symbol-editor.mjs';
import {inspectPinLabels,cleanupPinLabels} from '../lib/gdf-pin-labels.mjs';
import {tokeniseGdfGeometry,rebuildGdfGeometry,parseGdfGeometry} from '../lib/gdf-geometry.mjs';
import {createBlankGdf,constructGdf} from '../lib/gdf-authoring.mjs';
import {PlainMcpClient} from './helpers/plain-mcp.mjs';
import {sha256} from '../lib/workspace.mjs';
const pins=[{name:'DIN[7..0]',x:0,y:24,labelX:24,labelY:32,attributeName:'ISTUB'},{name:'Q[7..0]',x:240,y:24,labelX:96,labelY:32,attributeName:'OSTUB'}];
const clean=()=>createSymbol({name:'LABELTEST',width:240,height:64,pins,texts:[{text:'Keep comment',x:24,y:48}]}).buffer;
// Reconstruct the historic generator defect independently of the new authoring guard.
function historic(){const b=clean(),tokens=tokeniseGdfGeometry(b),pin=tokens.find(t=>t.opcode==='q'&&t.attrType===2),body=Buffer.from(pin.body);body[1]=0;body.writeUInt16LE(0x69,7);const h=tokens.findIndex(t=>t.opcode==='h');tokens.splice(h,0,{opcode:'q',nativeType:7,attrType:0,body});return rebuildGdfGeometry(tokens);}
test('native labels are visible; authored duplicate DOC is rejected with actionable guidance',()=>{const b=clean();assert.ok(inspectSymbol(b).pins.every(p=>p.labelDisplay.visible));assert.throws(()=>editSymbol(b,[{operation:'add_text',text:pins[0].name,x:24,y:32}]),/visible native pin label/);});
test('a different pin font does not bypass new DOC overlay prevention',()=>{const tokens=tokeniseGdfGeometry(clean()),pin=tokens.find(t=>t.opcode==='q'&&t.attrType===2);pin.body=Buffer.from(pin.body);pin.body[2]=1;const b=rebuildGdfGeometry(tokens);assert.throws(()=>editSymbol(b,[{operation:'add_text',text:pins[0].name,x:24,y:32}]),/visible native pin label/);});
test('delete only exact duplicate DOC; preserve all other record bodies and pin connection points',()=>{const b=historic(),d=inspectPinLabels(b);assert.equal(d.counts.duplicateRecords,1);const r=cleanupPinLabels(b);assert.equal(r.counts.after.duplicateRecords,0);assert.ok(inspectSymbol(r.buffer).texts.some(t=>t.text==='Keep comment'));assert.deepEqual(tokeniseGdfGeometry(r.buffer).map(t=>t.body),tokeniseGdfGeometry(b).filter(t=>t.offset!==d.duplicates[0].docOffset).map(t=>t.body));});
test('embedded shared definitions clean all instances including rotated copies and retain placement bytes',()=>{const sym=historic(),b=constructGdf(createBlankGdf(),[0,1,4].map((orientation,i)=>({operation:'add_symbol',symbolPath:'label.sym',symbolSha256:sha256(sym),name:'gate'+i,x:128+i*304,y:256,orientation})),()=>({path:'label.sym',bytes:sym})).buffer;assert.equal(inspectPinLabels(b).counts.renderedDuplicateLabels,3);const r=cleanupPinLabels(b,{alignOverlappingRightPins:true});assert.equal(r.counts.after.duplicateRecords,0);assert.equal(r.counts.after.sameRowPinCollisions,0);const points=g=>parseGdfGeometry(g).placements.map(p=>({name:p.instanceName,netId:p.netId,position:p.position,orientation:p.transform.code,pins:p.pins.map(p=>p.worldPosition)}));assert.deepEqual(points(r.buffer),points(b));});
test('root-sheet pin declarations count as rendered once without any placements',()=>{const blank=tokeniseGdfGeometry(createBlankGdf()),s=tokeniseGdfGeometry(historic()),end=s.findIndex(t=>t.opcode==='h'),b=rebuildGdfGeometry([blank[0],...s.slice(1,end),blank.at(-1)]);assert.equal(inspectPinLabels(b).counts.renderedDuplicateLabels,1);const r=cleanupPinLabels(b);assert.equal(r.counts.after.duplicateRecords,0);assert.equal(parseGdfGeometry(r.buffer).sheet.pins.length,2);});
test('align same-row opposing labels while preserving electrical points; cleanup is idempotent',()=>{const b=historic(),r=cleanupPinLabels(b,{alignOverlappingRightPins:true});assert.equal(r.counts.after.sameRowPinCollisions,0);assert.equal(inspectSymbol(r.buffer).pins[1].labelPosition.x,152);assert.deepEqual(inspectSymbol(r.buffer).pins.map(p=>p.position),inspectSymbol(b).pins.map(p=>p.position));assert.deepEqual(cleanupPinLabels(r.buffer,{alignOverlappingRightPins:true}).buffer,r.buffer);});
test('hidden DOC is retained and does not count as visible overlap',()=>{const b=historic(),offset=inspectPinLabels(b).duplicates[0].docOffset,r=editSymbol(b,[{operation:'set_text_display',recordOffset:offset,visible:false}]).buffer;assert.equal(inspectPinLabels(r).counts.duplicateRecords,0);assert.deepEqual(cleanupPinLabels(r).buffer,r);});
test('explicitly hiding the native label permits a separate custom DOC without deleting its electrical pin',()=>{const b=clean(),pin=inspectSymbol(b).pins[0],r=editSymbol(b,[{operation:'set_text_display',recordOffset:pin.attributeOffset,visible:false},{operation:'add_text',text:pin.name,x:pin.labelPosition.x,y:pin.labelPosition.y}]).buffer;assert.equal(inspectPinLabels(r).counts.duplicateRecords,0);assert.equal(inspectSymbol(r).pins.length,2);assert.deepEqual(cleanupPinLabels(r).buffer,r);});
test('different orientation is reported but not deleted',()=>{const b=historic(),offset=inspectPinLabels(b).duplicates[0].docOffset,r=editSymbol(b,[{operation:'set_text_display',recordOffset:offset,orientation:1}]).buffer;assert.equal(inspectPinLabels(r).duplicates[0].removable,false);assert.deepEqual(cleanupPinLabels(r).buffer,r);});
test('insufficient label space and unsupported versions refuse without mutating input',()=>{const b=createSymbol({name:'TIGHT',width:64,height:64,pins:[{...pins[0],name:'LONG_INPUT',labelX:8},{...pins[1],x:64,labelX:24}]}).buffer,copy=Buffer.from(b);assert.throws(()=>cleanupPinLabels(b,{alignOverlappingRightPins:true}),/Cannot safely separate/);assert.deepEqual(b,copy);const old=Buffer.from(historic());old.writeUInt16LE(5,6);assert.throws(()=>cleanupPinLabels(old),/version 6/);});
test('ordinary stdio MCP offers inspect/preview/hash guard/backup/apply independent of host computer use',async()=>{const workspace=fs.mkdtempSync(path.join(os.tmpdir(),'mp2-pinlabels-')),client=new PlainMcpClient(workspace),file=path.join(workspace,'label.sym'),b=historic();fs.writeFileSync(file,b);try{await client.initialize();const tools=(await client.request('tools/list')).tools;assert.ok(tools.some(t=>t.name==='gdf_pin_labels'));const inspect=await client.call('gdf_pin_labels',{path:'label.sym'});assert.equal(inspect.counts.duplicateRecords,1);const args={path:'label.sym',expectedSha256:sha256(b),alignOverlappingRightPins:true},preview=await client.call('gdf_pin_labels',args);assert.equal(preview.preview,true);assert.deepEqual(fs.readFileSync(file),b);const applied=await client.call('gdf_pin_labels',{...args,confirm:true});assert.ok(applied.backup);assert.equal((await client.call('gdf_pin_labels',{path:'label.sym'})).counts.duplicateRecords,0);const stale=await client.request('tools/call',{name:'gdf_pin_labels',arguments:{...args,confirm:true}});assert.equal(stale.isError,true);}finally{await client.close();}});
