import assert from 'node:assert/strict';
import test from 'node:test';
import {createHash} from 'node:crypto';
import {createSymbol,editSymbol,inspectSymbol} from '../lib/gdf-symbol-editor.mjs';
import {createBlankGdf,constructGdf} from '../lib/gdf-authoring.mjs';
import {parseGdfGeometry,tokeniseGdfGeometry,rebuildGdfGeometry} from '../lib/gdf-geometry.mjs';
import {inspectGdfSymbolRefresh,refreshGdfSymbol} from '../lib/gdf-symbol-refresh.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
const fresh=()=>createSymbol({name:'CUSTOM',width:64,height:48,pins:[{name:'A',attributeName:'ISTUB',x:0,y:24,labelX:8,labelY:25},{name:'Y',attributeName:'OSTUB',x:64,y:24,labelX:48,labelY:25}],graphics:[{operation:'add_circle',x:32,y:24,radius:4}],texts:[{text:'before',x:16,y:32}]}).buffer;
function drawing(sym=fresh(),n=3,ops=[],orientation=0){return constructGdf(createBlankGdf(),[...Array.from({length:n},(_,i)=>({operation:'add_symbol',symbolPath:'custom.sym',symbolSha256:sha(sym),name:`gate${i}`,x:128+i*160,y:256,orientation,...(i===0?{parameters:{WIDTH:1,VALUE:0}}:{})})),...ops],()=>({path:'custom.sym',bytes:sym})).buffer;}
function segment(bytes,name){const p=parseGdfGeometry(bytes),item=p.placements.find(p=>p.instanceName===name),ts=tokeniseGdfGeometry(bytes),at=ts.findIndex(t=>t.offset===item.offset),to=ts.findIndex((t,i)=>i>at&&['r','g','t'].includes(t.opcode));return rebuildGdfGeometry(ts.slice(at,to));}
const select=name=>({selectors:[{instanceName:name}]});
const graphicChange=b=>editSymbol(b,[{operation:'set_circle',recordOffset:inspectSymbol(b).graphics[0].offset,x:40,y:20,radius:6},{operation:'add_text',text:'new',x:4,y:4}]).buffer;

test('selective refresh splits a shared definition and preserves every instance r/h/u segment',()=>{
  const sym=fresh(),g=drawing(sym),next=graphicChange(sym),before=Buffer.from(g),plan=inspectGdfSymbolRefresh(g,next,select('gate1'));assert.equal(plan.canApply,true);assert.equal(plan.counts.definitionsBefore,1);assert.equal(plan.counts.definitionsAfter,3);assert.equal(plan.changes[0].graphChanged,true);assert.equal(plan.changes[0].pinChanges.length,0);
  const r=refreshGdfSymbol(g,next,select('gate1')),p=parseGdfGeometry(r.buffer);assert.deepEqual(p.placements.map(i=>i.instanceName),['gate0','gate1','gate2']);assert.equal(p.definitions[1].primitives[0].center.x,40);assert.equal(p.definitions[0].primitives[0].center.x,32);assert.equal(p.definitions[2].primitives[0].center.x,32);for(const n of ['gate0','gate1','gate2'])assert.deepEqual(segment(r.buffer,n),segment(g,n));assert.deepEqual(g,before);assert.deepEqual(r.buffer.subarray(0,20),g.subarray(0,20));
});
test('identical source graphics or changed ignored defaults produce an exact GDF no-op',()=>{
  const sym=fresh(),g=drawing(sym);assert.deepEqual(refreshGdfSymbol(g,sym,select('gate1')).buffer,g);const ts=tokeniseGdfGeometry(sym),id=ts.find(t=>t.nativeType===8&&t.attrType===41);id.body=Buffer.from(id.body);id.body[id.textRecord.payloadOffset-id.offset]=0x39;const r=refreshGdfSymbol(g,rebuildGdfGeometry(ts),select('gate1'));assert.deepEqual(r.buffer,g);assert.equal(r.changes[0].graphChanged,false);assert.equal(r.counts.definitionsAfter,1);
});
test('definitionIndex refreshes every shared instance with preserved names/IDs/position/orientation/parameters',()=>{
  const sym=fresh(),g=drawing(sym,3,[],3),next=graphicChange(sym),r=refreshGdfSymbol(g,next,{selectors:[{definitionIndex:0}]}),before=parseGdfGeometry(g),after=parseGdfGeometry(r.buffer);assert.equal(after.definitions.length,1);assert.equal(r.changes.length,3);for(let i=0;i<3;i++){assert.deepEqual(after.placements[i].position,before.placements[i].position);assert.equal(after.placements[i].transform.code,3);assert.equal(after.placements[i].netIdText,before.placements[i].netIdText);assert.deepEqual(after.placements[i].parameters.entries,before.placements[i].parameters.entries);assert.deepEqual(segment(g,`gate${i}`),segment(r.buffer,`gate${i}`));}
});
test('moved wired pin is reviewable, rejected by default, and explicitly acknowledged without moving wires',()=>{
  const sym=fresh(),g=drawing(sym,1,[{operation:'add_wire',x1:64,y1:280,x2:128,y2:280}]),A=inspectSymbol(sym).pins.find(p=>p.name==='A'),next=editSymbol(sym,[{operation:'set_pin',recordOffset:A.offset,x:0,y:32}]).buffer,plan=inspectGdfSymbolRefresh(g,next,select('gate0'));assert.equal(plan.canApply,false);assert.equal(plan.blockers[0].code,'geometric-contact-change');assert.equal(plan.changes[0].pinChanges[0].contacts.lost[0].at,'endpoint');assert.deepEqual(plan.changes[0].pinChanges[0].before.worldPosition,{x:128,y:280});assert.deepEqual(plan.changes[0].pinChanges[0].after.worldPosition,{x:128,y:288});
  assert.throws(()=>refreshGdfSymbol(g,next,select('gate0')),e=>e.preview?.canApply===false);const r=refreshGdfSymbol(g,next,{...select('gate0'),allowDisconnected:true});assert.deepEqual(parseGdfGeometry(r.buffer).sheet.wires,parseGdfGeometry(g).sheet.wires);assert.deepEqual(segment(r.buffer,'gate0'),segment(g,'gate0'));
});
test('pin shift on the same wire interior retains its geometric contact without an override',()=>{
  const sym=fresh(),g=drawing(sym,1,[{operation:'add_wire',x1:64,y1:280,x2:192,y2:280}]),next=editSymbol(sym,[{operation:'set_pin',recordOffset:inspectSymbol(sym).pins[0].offset,x:8,y:24}]).buffer,plan=inspectGdfSymbolRefresh(g,next,select('gate0'));assert.equal(plan.canApply,true);assert.equal(plan.changes[0].pinChanges[0].contacts.before[0].at,'interior');assert.equal(plan.changes[0].pinChanges[0].contacts.after[0].at,'interior');assert.equal(plan.changes[0].pinChanges[0].contacts.lost.length,0);
});
test('moving from a wire endpoint into its interior still requires explicit alignment acknowledgement',()=>{
  const sym=fresh(),g=drawing(sym,1,[{operation:'add_wire',x1:64,y1:280,x2:128,y2:280}]),next=editSymbol(sym,[{operation:'set_pin',recordOffset:inspectSymbol(sym).pins[0].offset,x:-8,y:24}]).buffer,p=inspectGdfSymbolRefresh(g,next,select('gate0'));assert.equal(p.canApply,false);assert.equal(p.changes[0].pinChanges[0].contacts.alignmentChanges[0].before,'endpoint');assert.equal(p.changes[0].pinChanges[0].contacts.alignmentChanges[0].after,'interior');
});
test('new contact to an existing electrical wire is explicit even when the old pin was unconnected',()=>{
  const sym=fresh(),g=drawing(sym,1,[{operation:'add_wire',x1:64,y1:288,x2:128,y2:288}]),next=editSymbol(sym,[{operation:'set_pin',recordOffset:inspectSymbol(sym).pins[0].offset,x:0,y:32}]).buffer,p=inspectGdfSymbolRefresh(g,next,select('gate0'));assert.equal(p.canApply,false);assert.equal(p.changes[0].pinChanges[0].contacts.added.length,1);assert.equal(p.changes[0].pinChanges[0].contacts.lost.length,0);
});
test('pin additions/removals/direction changes require interface acknowledgement independently of contacts',()=>{
  const sym=fresh(),g=drawing(sym,1),s=inspectSymbol(sym),next=editSymbol(sym,[{operation:'delete_pin',recordOffset:s.pins[0].offset},{operation:'set_pin',recordOffset:s.pins[1].offset,attributeName:'IOSTUB'},{operation:'add_pin',name:'B',attributeName:'ISTUB',x:0,y:8,labelX:8,labelY:9}]).buffer,p=inspectGdfSymbolRefresh(g,next,select('gate0'));assert.equal(p.canApply,false);assert.ok(p.blockers.some(b=>b.code==='interface-change'));assert.deepEqual(p.changes[0].interfaceChanges.added.map(p=>p.name),['B']);assert.deepEqual(p.changes[0].interfaceChanges.removed.map(p=>p.name),['A']);assert.equal(p.changes[0].interfaceChanges.changed[0].after.nativeAttributeType,4);assert.equal(inspectGdfSymbolRefresh(g,next,{...select('gate0'),allowDisconnected:true}).canApply,false);assert.equal(inspectGdfSymbolRefresh(g,next,{...select('gate0'),allowInterfaceChanges:true}).canApply,true);
});
test('pin rename retains geometry but is reported as removal/addition and needs acknowledgement',()=>{
  const sym=fresh(),g=drawing(sym,1),next=editSymbol(sym,[{operation:'set_pin',recordOffset:inspectSymbol(sym).pins[0].offset,name:'IN'}]).buffer,p=inspectGdfSymbolRefresh(g,next,select('gate0'));assert.equal(p.canApply,false);assert.equal(p.changes[0].interfaceChanges.removed[0].name,'A');assert.equal(p.changes[0].interfaceChanges.added[0].name,'IN');assert.equal(p.changes[0].pinChanges.length,2);
});
test('label anchor changes are reported while unused SYM default changes do not rewrite old instances',()=>{
  const sym=fresh(),g=drawing(sym,1),s=inspectSymbol(sym),changed=editSymbol(sym,[{operation:'set_pin',recordOffset:s.pins[0].offset,labelX:12,labelY:26}]).buffer,tokens=tokeniseGdfGeometry(changed),id=tokens.find(t=>t.nativeType===8&&t.attrType===41);id.body=Buffer.from(id.body);id.body[id.textRecord.payloadOffset-id.offset]=0x39;const source=rebuildGdfGeometry(tokens),r=refreshGdfSymbol(g,source,select('gate0'));assert.ok(r.changes[0].pinChanges[0].fields.includes('labelPosition'));assert.equal(r.changes[0].interfaceChanges.changedInterface,false);assert.deepEqual(segment(g,'gate0'),segment(r.buffer,'gate0'));assert.equal(parseGdfGeometry(r.buffer).placements[0].netIdText,'1');
});
test('preserved instance pin defaults cannot be orphaned even with both safety flags',()=>{
  const sym=fresh(),g=drawing(sym,1),ts=tokeniseGdfGeometry(g),pin=ts.find(t=>t.nativeType===7&&t.attrType===2),h=ts.findIndex(t=>t.opcode==='h');ts.splice(h+1,0,{opcode:'q',body:Buffer.from(pin.body)});const withDefault=rebuildGdfGeometry(ts),next=editSymbol(sym,[{operation:'delete_pin',recordOffset:inspectSymbol(sym).pins[0].offset}]).buffer,p=inspectGdfSymbolRefresh(withDefault,next,{...select('gate0'),allowDisconnected:true,allowInterfaceChanges:true});assert.equal(p.canApply,false);assert.ok(p.blockers.some(b=>b.code==='orphaned-instance-pin-default'));assert.throws(()=>refreshGdfSymbol(withDefault,next,{...select('gate0'),allowDisconnected:true,allowInterfaceChanges:true}),/orphaned-instance-pin-default/);
});
test('world contact comparisons include direct pin overlap and all native orientation/extent changes',()=>{
  const sym=fresh(),g=constructGdf(createBlankGdf(),[{operation:'add_symbol',symbolPath:'a',symbolSha256:sha(sym),name:'one',x:128,y:256},{operation:'add_symbol',symbolPath:'a',symbolSha256:sha(sym),name:'two',x:192,y:256}],()=>({path:'a',bytes:sym})).buffer,next=editSymbol(sym,[{operation:'set_pin',recordOffset:inspectSymbol(sym).pins.find(p=>p.name==='Y').offset,x:72,y:24}]).buffer,p=inspectGdfSymbolRefresh(g,next,select('one'));assert.equal(p.canApply,false);assert.ok(p.changes[0].pinChanges.find(p=>p.before?.name==='Y').contacts.lost.some(c=>c.kind==='pin'&&c.instanceName==='two'));
  for(let orientation=0;orientation<8;orientation++){const g=drawing(sym,1,[],orientation),changed=editSymbol(sym,[{operation:'set_extent',width:80,height:64}]).buffer,r=refreshGdfSymbol(g,changed,select('gate0')),after=parseGdfGeometry(r.buffer);assert.equal(after.placements[0].transform.code,orientation);assert.deepEqual(after.placements[0].position,{x:128,y:256});assert.ok(after.placements[0].pins.every(p=>p.worldPosition));}
});
test('mixed offset/name selection is bounded and malformed, overlapping and different-type replacements fail',()=>{
  const sym=fresh(),g=drawing(sym),p=parseGdfGeometry(g),next=graphicChange(sym),r=refreshGdfSymbol(g,next,{selectors:[{recordOffset:p.placements[0].offset},{instanceName:'gate2'}]});assert.equal(r.changes.length,2);for(const opts of [{selectors:[]},{selectors:Array(1001).fill({instanceName:'gate0'})},{selectors:[{definitionIndex:0},{instanceName:'gate0'}]},{selectors:[{instanceName:'missing'}]},{selectors:[{recordOffset:0}]},{selectors:[{recordOffset:p.placements[0].offset,definitionIndex:0}]},{selectors:[{instanceName:'gate0'}],extra:true},{selectors:[{instanceName:'gate0'}],allowDisconnected:1}])assert.throws(()=>refreshGdfSymbol(g,next,opts));assert.throws(()=>refreshGdfSymbol(sym,next,select('gate0')),/GDF version 6/);assert.throws(()=>refreshGdfSymbol(g,createSymbol({name:'OTHER'}).buffer,select('gate0')),/same symbol name/);assert.throws(()=>refreshGdfSymbol(g,createSymbol({name:'CUSTOM',nameAttributeName:'SYM_NAME'}).buffer,select('gate0')),/same symbol name/);
});
