import {PACKAGE_VERSION} from './helpers/package-version.mjs';
/** Ordinary MCP stdio exercises the complete new file workflows and validates
 * routed drawings/SCF stimuli with the original compiler and simulator. */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {PlainMcpClient} from './helpers/plain-mcp.mjs';
import {sha256} from '../lib/workspace.mjs';
import {parseTbl,tblTrace} from '../lib/tbl.mjs';
const workspace=fs.mkdtempSync(path.join(os.tmpdir(),'mp2-v09-client-')),client=new PlainMcpClient(workspace);let passed=0,project,baseline,gate;
const call=(n,a)=>client.call(n,a),job=(n,a)=>client.job(n,a);
async function check(label,fn){await fn();passed++;console.log('PASS '+label);}
async function error(n,a,re){const r=await client.request('tools/call',{name:n,arguments:a});assert.equal(r.isError,true);assert.match(r.content[0].text,re);}
function truth(result){assert.equal(result.verdict,'verified',JSON.stringify(result));assert.deepEqual(result.counts,{errors:0,warnings:0});const trace=tblTrace(parseTbl(fs.readFileSync(result.tblPath,'latin1')));for(const [i,time]of [50,150,250,350].entries()){const row=trace.filter(r=>r.time<=time).at(-1);assert.ok(row);assert.equal(row.rawInputs.A[0],String(i>>1));assert.equal(row.rawInputs.B[0],String(i&1));assert.equal(row.rawValues.Y,String((i>>1)^(i&1)));}}
try{
 await check('68 tools on ordinary MCP include all source/font/SCF workflows and appropriate annotations',async()=>{assert.equal((await client.initialize()).serverInfo.version,PACKAGE_VERSION);const ts=(await client.request('tools/list')).tools;assert.equal(ts.length,68);for(const n of ['gdf_connections','gdf_move_connected','gdf_text_format_inspect','gdf_text_format_edit','scf_editor_metadata','scf_stimulus_edit','scf_compiled_ports','scf_ports_import','scf_from_compiled_create'])assert.ok(ts.some(t=>t.name===n));assert.equal(ts.find(t=>t.name==='gdf_move_connected').annotations.destructiveHint,true);assert.equal(ts.find(t=>t.name==='scf_from_compiled_create').annotations.destructiveHint,false);});
 await check('new XOR schematic returns source pin connections with exact original identity',async()=>{project=await call('project_create',{name:'demo',device:'EP1K10TC100-1',confirm:true});const b=await call('gdf_create',{project:project.project,path:'demo.gdf',confirm:true}),ops=[];for(const [s,name,x,y,nodeName]of [['input','inputA',32,296,'A'],['input','inputB',32,280,'B'],['xor','gate',272,280],['output','outputY',408,288,'Y']]){const source=await call('gdf_symbol_library',{path:`prim/${s}.sym`,limit:100});ops.push({operation:'add_symbol',symbolPath:source.path,symbolSha256:source.sha256,name,x,y,...(nodeName?{nodeName}:{})});}for(const [x1,y1,x2,y2]of [[200,304,272,304],[200,288,272,288],[336,296,408,296]])ops.push({operation:'add_wire',x1,y1,x2,y2});await call('gdf_construct',{project:project.project,path:'demo.gdf',expectedSha256:b.sha256,operations:ops,confirm:true});const m=await call('gdf_connections',{project:project.project,path:'demo.gdf',limit:100});assert.equal(m.completeScalarTopology,true);assert.equal(m.bitTopology.complete,true);assert.deepEqual(m.nets.items.map(n=>n.terminalKeys.items.length),[2,2,2]);baseline=fs.readFileSync(m.path);gate=(await call('gdf_geometry',{project:project.project,path:'demo.gdf',view:'placements',limit:100})).records.items.find(p=>p.instanceName==='gate');});
 await check('compile and export original ports, then create a no-VEC SCF with actual output observations',async()=>{assert.equal((await job('maxplus2_run',{project:project.project,compile:true})).report.clean,true);const exported=await job('netlist_export',{project:project.project,path:'demo.gdf'});assert.equal(exported.verdict,'verified-export');const edo=exported.exportPaths.find(p=>p.extension==='.edo');assert.ok(edo);fs.copyFileSync(edo.path,path.join(project.directory,'demo.edo'));const catalog=await call('scf_compiled_ports',{project:project.project,path:'demo.edo',limit:100});assert.equal(catalog.complete,true);assert.deepEqual(catalog.nodes.items.map(n=>n.name),['A','B','Y']);const args={project:project.project,path:'demo.scf',edifPath:'demo.edo',edifSha256:catalog.sha256,durationNs:400};const p=await call('scf_from_compiled_create',args);assert.equal(p.preview,true);assert.equal(fs.existsSync(path.join(project.directory,'demo.scf')),false);await error('scf_from_compiled_create',{...args,edifSha256:'0'.repeat(64),confirm:true},/EDIF changed/);const r=await call('scf_from_compiled_create',{...args,confirm:true});assert.equal(r.result.sha256,p.nextSha256);await error('scf_from_compiled_create',{...args,confirm:true},/exists/);assert.equal(fs.existsSync(path.join(project.directory,'demo.vec')),false);});
 await check('SCF counter creates independently expected inputs and vendor computes all four XOR outputs',async()=>{const m=await call('scf_editor_metadata',{project:project.project,path:'demo.scf'});assert.ok(m.unknownEditorFields.items.includes('cursor positions'));const args={project:project.project,path:'demo.scf',expectedSha256:m.sha256,operations:[{type:'counter',signals:['A','B'],intervalNs:100}]},p=await call('scf_stimulus_edit',args),r=await call('scf_stimulus_edit',{...args,confirm:true});assert.equal(r.result.sha256,p.nextSha256);assert.equal(sha256(fs.readFileSync(r.backup)),m.sha256);truth(await job('simulate_and_verify',{project:project.project}));});
 await check('connected move previews source equivalence, applies/backs up, and passes original XOR truth table',async()=>{const m=await call('gdf_connections',{project:project.project,path:'demo.gdf'}),args={project:project.project,path:'demo.gdf',expectedSha256:m.sha256,edits:[{recordOffset:gate.offset,dy:64}]};const p=await call('gdf_move_connected',args);assert.equal(p.connectionCheck.preserved,true);assert.ok(p.connectionCheck.addedSegments>0);assert.deepEqual(fs.readFileSync(path.join(project.directory,'demo.gdf')),baseline);const r=await call('gdf_move_connected',{...args,confirm:true});assert.equal(r.result.sha256,p.nextSha256);assert.equal(sha256(fs.readFileSync(r.backup)),m.sha256);assert.equal((await job('maxplus2_run',{project:project.project,compile:true})).report.clean,true);truth(await job('simulate_and_verify',{project:project.project}));await call('project_restore_file',{project:project.project,path:'demo.gdf',backup:r.backup,backupSha256:m.sha256,expectedSha256:r.result.sha256,confirm:true});assert.deepEqual(fs.readFileSync(path.join(project.directory,'demo.gdf')),baseline);});
 await check('all eight rotations/mirrors and two horizontal shortenings retain independent vendor XOR truth',async()=>{for(const edit of [...Array.from({length:8},(_,orientation)=>({dx:16,dy:64,orientation})),{dx:32},{dx:-32}]){const args={project:project.project,path:'demo.gdf',expectedSha256:sha256(baseline),edits:[{recordOffset:gate.offset,...edit}],confirm:true};const r=await call('gdf_move_connected',args);assert.equal(r.connectionCheck.preserved,true);const c=await job('maxplus2_run',{project:project.project,compile:true});assert.equal(c.report.clean,true,JSON.stringify(c));truth(await job('simulate_and_verify',{project:project.project}));await call('project_restore_file',{project:project.project,path:'demo.gdf',backup:r.backup,backupSha256:sha256(baseline),expectedSha256:r.result.sha256,confirm:true});}});
 await check('Chinese DOC and Windows fonts use fresh hash/preview/backup and preserve electrical geometry',async()=>{const before=sha256(baseline),args={project:project.project,path:'demo.gdf',expectedSha256:before,operations:[{operation:'add_text',x:32,y:480,text:'中文原理图 字体测试',encoding:'windows-936',fontSpecification:'宋体,18',width:264,height:24}]},p=await call('gdf_text_format_edit',args),r=await call('gdf_text_format_edit',{...args,confirm:true});assert.equal(r.result.sha256,p.nextSha256);const t=await call('gdf_text_format_inspect',{project:project.project,path:'demo.gdf',encoding:'windows-936',limit:100});assert.ok(t.attributes.items.some(a=>a.text.value==='中文原理图 字体测试'));await error('gdf_text_format_edit',{...args,confirm:true},/changed/);await call('project_restore_file',{project:project.project,path:'demo.gdf',backup:r.backup,backupSha256:before,expectedSha256:r.result.sha256,confirm:true});});
 await check('second-file freshness and scope guards preserve both source files on failed compiled import',async()=>{const pathScf=path.join(project.directory,'demo.scf'),before=sha256(fs.readFileSync(pathScf)),edo=sha256(fs.readFileSync(path.join(project.directory,'demo.edo'))),args={project:project.project,path:'demo.scf',expectedSha256:before,edifPath:'demo.edo',edifSha256:edo};await error('scf_ports_import',{...args,edifSha256:'0'.repeat(64),confirm:true},/EDIF changed/);await error('scf_ports_import',{...args,edifPath:path.join(workspace,'outside.edo'),confirm:true},/escapes/);assert.equal(sha256(fs.readFileSync(pathScf)),before);const r=await call('scf_ports_import',{...args,confirm:true});assert.equal(r.result.sha256,before);await error('gdf_move_connected',{project:project.project,path:'demo.gdf',expectedSha256:sha256(baseline),edits:[{recordOffset:gate.offset,dy:16}],confirm:true},/overlaps/);assert.deepEqual(fs.readFileSync(path.join(project.directory,'demo.gdf')),baseline);});
 await check('empty Windows-font DOC width0 is accepted and electrical names remain protected',async()=>{const b=await call('gdf_create',{path:'empty.gdf',confirm:true});const r=await call('gdf_text_format_edit',{path:'empty.gdf',expectedSha256:b.sha256,operations:[{operation:'add_text',x:0,y:0,text:'',fontSpecification:'Arial,18',width:0,height:25}],confirm:true});assert.ok(r.result.sha256);const m=await call('gdf_text_format_inspect',{project:project.project,path:'demo.gdf',limit:100});const electrical=m.attributes.items.find(a=>a.attributeCode===5);assert.ok(electrical);await error('gdf_text_format_edit',{project:project.project,path:'demo.gdf',expectedSha256:m.sha256,operations:[{operation:'set_font',recordOffset:electrical.recordOffset,fontCode:2}],confirm:true},/free root/);});
 console.log(`OK passed=${passed} failed=0\nScratch retained: ${workspace}`);
}finally{await client.close();}
